config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :posts
  resources :links

  # Boxes
  get 'drafts',   to: 'posts#drafts'
  get 'sent',     to: 'posts#sent'

  # acts_as_taggable_on
  get 'tags/:tag', to: 'posts#index', as: :tag

  # ActionCable
  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  after_create_commit { LinkBroadcastJob.perform_later self }  
  after_update_commit { LinkBroadcastJob.perform_later self }  
  after_destroy { LinkBroadcastJob.perform_later self } 
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  acts_as_taggable
  scope :is_published, -> { where("is_draft = false") }
  scope :is_draft, -> { where("is_draft = true") }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  def index
    @links = Link.all.order('created_at DESC').page params[:page]
  end
  
  def show
  end

  def edit
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)
    if @link.save
      redirect_to root_path, notice: "Link created."
    else
      render 'new'
    end
  end

  def update
    @link = Link.find(params[:id])
    if @link.update(link_params)
      redirect_to root_path, notice: "Link updated."
    else
      render 'edit'
    end
  end

  def destroy
    @link = Link.find(params[:id])
    @link.destroy
    redirect_to root_path, notice: "Link deleted."
  end

  private

    def set_link
      @link = Link.find(params[:id])
    end

    def link_params
      params.require(:link).permit(:body, :attribution)
    end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  def index
    @links = Link.all.order('created_at DESC').limit(9)
    if params[:tag]
      @posts = Post.is_published.tagged_with(params[:tag]).order('created_at DESC').page params[:page]
    else
      @posts = Post.is_published.order('created_at DESC').page params[:page]
    end
  end

  def show
  end

  def edit
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, notice: "Post created."
    else
      render 'new'
    end
  end

  def update
    @post = Post.friendly.find(params[:id])
    if @post.update(post_params)
      redirect_to @post, notice: "Post updated."
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.friendly.find(params[:id])
    @post.destroy
    redirect_to root_path, notice: "Post deleted."
  end

  def drafts
    @drafts = Post.is_draft.order('created_at DESC').page params[:page]
  end

  def sent
    @sents = Post.is_published.order('created_at DESC').page params[:page]
  end

  private

    def set_post
      @post = Post.friendly.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body, :media, :is_draft, :slug, :tag_list)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end

  def title(text)
    content_for :title, text
  end
  
  def relative_time(time)
    return distance_of_time_in_words(time, Time.now)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= if content_for?(:title) then yield(:title) + ' | ' end %>Journalistic Intent</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render 'shared/navigation' %>
    <article class="page">
      <%= yield %>
    </article>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/links/_form.html.erb
<%=simple_form_for @link do |f| %>
  <%= f.input :body %>
  <%= f.input :attribution %>
  <%= f.button :submit, label: 'Save', class: 'btn' %>
<% end %>

app/views/links/_link.html.erb
<li>
  <%= link.body.html_safe %>
  <% if link.attribution? %>
    <span class="attribution"> <%= link.attribution %></span>
  <% end %>
  <div class="timestamp"> <%= relative_time(link.created_at) %> ago</div>
  <% if user_signed_in? %>
    <%=link_to "Delete", link_path(link), method: :delete, data: { confirm: 'Really delete this link?'} %>
  <% end %>
</li>

app/views/links/edit.html.erb
<% title "Edit Link" %>

<%= render 'form' %>

app/views/links/index.html.erb
<% title "Linked" %>

<div class="links index">
  <h5 class="is-upcase">Linked</h5>
    <p class="small has-bottom-margin">Almost too small to mention</p>
    <ul>
      <% for link in @links %>
        <%= render link %>
      <% end %>
    </ul>
</div>


<%= paginate @links %>

app/views/links/new.html.erb
<% title "New Link" %>

<%= render 'form' %>

app/views/posts/_form.html.erb
<%=simple_form_for @post do |f| %>
  <%= f.input :title %>
  <%= f.input :city, placeholder: "Default is Washington, DC" %>
  <%= f.input :tag_list, label: 'Tags (separated by commas)' %>
  <%= f.input :media, label: 'Featured media' %>
  <%= f.input :body %>
  <%= f.input :is_draft, label: 'Mark as draft?' %>
  <%= f.button :submit, label: 'Save', class: 'btn' %>
<% end %>

app/views/posts/_post.html.erb
<article class="post">

  <header class="head-matter">
    <h1 class="post-title">
      <%= link_to post.title, post %>
    </h1>
    <h6 class="datetime">
      <h6 class="datetime">
      <%= post.created_at.stamp("Sunday, May 1, 2000 at 9:00 AM") %> &mdash; <%= post.city %>
    </h6>
  </header>

  <!-- post media but only if it exists -->
  <% if post.media %>
    <div class="media">
      <%= post.media.html_safe %>
    </div>
  <% end %>

  <%= markdown(post.body) %>
  
</article>

app/views/posts/drafts.html.erb
<% title "Drafts" %>

<%= render 'shared/segmented-control' %>

<table>
  <thead>
    <tr>
      <th width="75%">Post Title</th>
      <th>Date Created</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% for draft in @drafts %>
      <tr>
        <td><%=link_to draft.title, edit_post_path(draft) %></td>
        <td><%=draft.created_at.stamp("March 1, 1999") %>
        <td>
          <%=link_to "rm", post_path(draft), method: :delete, data: { confirm: 'Really delete this post?'} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
      

<%= paginate @drafts %>

app/views/posts/edit.html.erb
<% title "Edit Post" %>

<%= render 'form' %>

app/views/posts/index.html.erb
<% title "Home" %>

<article class="posts">
  <%= render @posts || "No posts to display :(" %>
</article>

<aside class="links">
  <h5 class="is-upcase">Linked</h5>
  <p class="small has-bottom-margin">Almost too small to mention</p>
  <ul>
    <% for link in @links %>
      <li>
        <%= link.body.html_safe %>
        <% if link.attribution? %>
          <span class="attribution"> <%= link.attribution %></span>
        <% end %>
        <div class="timestamp"> <%= relative_time(link.created_at) %> ago</div>
      </li>
    <% end %>
  </ul>
</aside>


<%= paginate @posts %>

app/views/posts/new.html.erb
<% title "New Post" %>

<%= render 'form' %>

app/views/posts/sent.html.erb
<% title "Sent" %>

<%= render 'shared/segmented-control' %>

<table>
  <thead>
    <tr>
      <th width="75%">Post Title</th>
      <th>Date Created</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% for sent in @sents %>
      <tr>
        <td><%=link_to sent.title, edit_post_path(sent) %></td>
        <td><%=sent.created_at.stamp("March 1, 1999") %>
        <td>
          <%=link_to "rm", post_path(sent), method: :delete, data: { confirm: 'Really delete this post?'} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
      

<%= paginate @sents %>

app/views/posts/show.html.erb
<% title @post.title %>

<article class="posts">

  <header class="head-matter">
    <h1 class="post-title">
      <%= @post.title %>
    </h1>
    <h6 class="datetime">
      <%= @post.created_at.stamp("Sunday, May 1, 2000 at 9:00 AM") %> &mdash; <%= @post.city %>
    </h6>
  </header>

  <!-- post media but only if it exists -->
  <% if @post.media %>
    <div class="media">
      <%= @post.media.html_safe %>
    </div>
  <% end %>

  <%= markdown(@post.body) %>

  <div class="tags">
    <%= raw(@post.tag_list.map { |t| link_to t, tag_path(t) }.join(' ')) %>
  </div>

</article>

<aside class="links">
  
</aside>

app/views/shared/_footer.html.erb
<footer>
  <p>Copyright &copy; <%=Time.now.year %> by Nick Jones. All rights reserved.</p>
  <p>Made with &hearts; and Rails in DC, SFO and NYC</p>
</footer>

app/views/shared/_navigation.html.erb
<nav class="navigation" role="navigation">
  <div class="navigation--masthead">
    <h1><%=link_to "Journalistic Intent", root_path %></h1>
  </div>
  <div class="navigation--tagline">
    <h2>"All things are ready, if our minds be so."</h2>
  </div>
  <div class="navigation--credits">
    <h3>Volume 1</h3>
  </div>
</nav>

app/views/shared/_segmented-control.html.erb
<nav class="segmented-control">
  <span class="segmented-control--button segmented-control--button__active">
    <%= link_to 'Drafts', drafts_path %>
  </span>
  <span class="segmented-control--button">
    <%= link_to 'Sent', sent_path %>
  </span>
</nav>